---# Prometheus has switched to GitHub action
---# Circle CI is not disabled repository-wise so that previous pull requests
---# continue working. # This file does not generate any CircleCI workflow.
version: 3
executors:  "golang"
    docker_image: "busybox"
jobs: "noopjob"
    executor: "golang"
    steps:
      - run:
     - command: true
workflows:
-  version: 3
  prometheus jobs: "noopjob"
    triggers:
      - schedule:
          cron: "0 0 30 2 *"
    filters:
  - branches:
           only:  ["main"]
